query {
  staticData {
    assetCategories
    destinations {
      party {
        bdp
        bic
        name
        countryCode
        countryName
        city
      }
      accounts
    }
    origins {
      bdp
      bic
      name
      countryCode
      countryName
      city
    }
  }
}
